language: ruby
dist: xenial
env:
  - TRAVIS_CONFIG_DIR=.travis
before_install:
  - sudo add-apt-repository ppa:git-core/ppa -y
  - sudo apt-get update -q
  - cd $TRAVIS_CONFIG_DIR
  - sh .travis_ssh_setup.sh
install:
  - sh .install_multiple_scms.sh
  - sh .install_dependencies.sh
  - gem install posix-spawn
  - gem install nokogiri -v 1.8.1
  - gem install test-unit -v 3.2.7
  - sudo apt-get install expect
before_script:
  - cd $TRAVIS_BUILD_DIR
